wifi.setmode(wifi.STATION)

wifi.sta.config("IvanWireless","unbreakable")
wifi.sta.connect()
tmr.delay(2000000)
print(wifi.ap.getip())

file.remove("connected.lua")
file.open("connected.lua","w")

file.writeline([[print("starting connected server")]])
file.writeline([[gpio.mode(3, gpio.OUTPUT)]])
file.writeline([[gpio.write(3, gpio.HIGH)]])
file.writeline([[tmr.delay(2000000)]])
file.writeline([[gpio.write(3,gpio.LOW)]])
file.writeline([[tmr.delay(1000000)]])
file.writeline([[gpio.write(3,gpio.HIGH)]])
file.writeline([[tmr.delay(2000000)]])
file.writeline([[gpio.write(3,gpio.LOW)]])
file.writeline([[tmr.delay(1000000)]])
file.writeline([[gpio.write(3,gpio.HIGH)]])
file.writeline([[tmr.delay(2000000)]])
file.writeline([[gpio.write(3,gpio.LOW)]])
file.writeline([[tmr.delay(1000000)]])
file.writeline([[gpio.write(3,gpio.HIGH)]])
file.writeline([[tmr.delay(2000000)]])
file.writeline([[gpio.write(3,gpio.LOW)]])
file.close()

file.remove("init.lua")
file.open("init.lua","w")
tmr.delay(1000000)
file.writeline([[dofile("connected.lua")]])


file.close()
node.restart()
